easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Item
        - App\Entity\Category
        - App\Entity\SubCategory
        - App\Entity\User
        - App\Entity\Client
        - App\Entity\Project
        - App\Entity\Address
        - App\Entity\Zone
        - App\Entity\Subzone
        - App\Entity\Service
        - App\Entity\Subservice
        - App\Entity\Type
        - App\Entity\Configuration
